### ISSUE TITLE
"Auto correct current file" does nothing

### ISSUE THREAD

**Issue by ocarreterom** [pderichs/sublime_rubocop#68]
##### Please add some general information about your environment:

- Operating System - macOS 12.4
- Sublime Text version - 4126
- Details about your config e.g. do you use rbenv, rvm or your_own_command to run rubocop? rvm

##### Steps to reproduce:
The command "Check current file" works ok, but "Auto correct current file" does nothing.

```yml
# .rubocop.yml
require:
  - rubocop-rails
  - rubocop-rspec
  - standard

inherit_gem:
  standard: config/base.yml
```

Running `rubocop -a` in the console works ok.
